### ISSUE TITLE
能否提供ubuntu版本的clash

### ISSUE THREAD

**Issue by lDarryll** [zhaoweih/Clash-Copy#2]
能否提供ubuntu版本的clash

**Comment by SophonTec** [comment]
Same here!

**Comment by zhaoweih** [comment]
@lDarryll @SophonTec linux版本没有备份，需要的话可以google搜下clash linux备份应该就有
下面是我搜的可以参考下:
https://github.com/Elegycloud/clash-for-linux-backup

**Comment by lDarryll** [comment]
> @lDarryll @SophonTec linux版本没有备份，需要的话可以google搜下clash linux备份或者clash内核备份应该就有 下面是我搜的可以参考下: https://github.com/Elegycloud/clash-for-linux-backup

tks
