### ISSUE TITLE
ClashXPro-v1.118.1.1.dmg 是否完美支持mac m1

### ISSUE THREAD

**Issue by DeShuiYu** [zhaoweih/Clash-Copy#3]
ClashXPro-v1.118.1.1.dmg 是基于arm64架构的还是基于x86-64架构的，能否完美支持mac m1芯片

**Comment by zhaoweih** [comment]
支持的

DeShuiYu ***@***.***>于2024年7月9日 周二下午7:59写道：

**Comment by zhaoweih** [comment]
@DeShuiYu universal的，intel芯片和m系列都可以用的
